name: Build and Deploy
run-name: Build and deploy docker images on dockerhub

on: [push]
jobs:
    build_base_job:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Autenticate with Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
          - name: Get debian-novnc Base Files
            run: wget git@github.com:B0nam/DEBIAN-DOCKER-NOVNC.git

          - name: Build debian-novnc Base
            run: docker build -t debian-novnc:base DEBIAN-DOCKER-NOVNC/Base/.
  
          - name: Push debian-novnc Base
            run: |
              docker tag debian-novnc:base "${{ secrets.DOCKERHUB_USERNAME }}/debian-novnc:base"
              docker push "${{ secrets.DOCKERHUB_USERNAME }}/debian-novnc:base"

    build_doom_job:
      needs: build_base_job
      runs-on: ubuntu-latest

      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Autenticate with Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Build debian-doom image
            run: docker build -t debian-doom:latest Docker/.

          - name: Push debian-doom image
            run: |
              docker tag debian-doom:latest "${{ secrets.DOCKERHUB_USERNAME }}/debian-doom:latest"
              docker push "${{ secrets.DOCKERHUB_USERNAME }}/debian-doom:latest"
